# Permalinks
permalink:           pretty

# Setup
title:               Nancy Chauhan
tagline:             Developer
url:                 https://nancy-chauhan.github.io/
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Nancy Chauhan
  email:             nancychn1@gmail.com

# Custom vars
version:             2.0.1
github:
  repo:              https://github.com/Nancy-Chauhan/nancy-chauhan.github.io
google_analytics:    UA-3363703-15


# Gems
plugins:
  # - jekyll-paginate
  # - jekyll-gist
